#pragma once

#include <Arduino.h>

// Application screens. Keeping the modes in a dependency-light header lets
// navigation and menu metadata evolve without pulling the full global state
// into every module.
enum AppMode {
    APP_MODE_BAND_SELECT,
    APP_MODE_MENU,
    APP_MODE_SUBGHZ_OFFLINE,
    APP_MODE_SUBGHZ,
    APP_MODE_SUBGHZ_ANALYZER,
    APP_MODE_SUBGHZ_RECORD,
    APP_MODE_SUBGHZ_EMULATE,
    APP_MODE_SUBGHZ_PRESETS,
    APP_MODE_SUBGHZ_PACKET,
    APP_MODE_SUBGHZ_RF_TEST,
    APP_MODE_JAMMER,
    APP_MODE_ANALYZER_SPECTRUM,
    APP_MODE_WATERFALL,
    APP_MODE_ANALYZER_CHANNEL,
    APP_MODE_SURVEY,
    APP_MODE_EVENTS,
    APP_MODE_LOGGING,
    APP_MODE_RADIO_DIAG,
    APP_MODE_PROFILES,
    APP_MODE_SETTINGS,
    APP_MODE_ANIMATION_SETTINGS,
    APP_MODE_STATUS,
    APP_MODE_POWER,
    APP_MODE_ENV_OCCUPANCY,
    APP_MODE_ENV_HEATMAP,
    APP_MODE_ENV_BURSTS,
    APP_MODE_ENV_COMPARE,
    APP_MODE_ENV_STATUS,
    APP_MODE_ENV_BEFORE_AFTER,
    APP_MODE_ENV_BAND_INFO,
    APP_MODE_ENV_PROBE,
    APP_MODE_LUA_SCRIPTS,
    APP_MODE_FILE_EXPLORER,
    APP_MODE_PACKET_SNIFFER,
    APP_MODE_DATA_MENU,
    APP_MODE_SESSION_MANAGER,
    APP_MODE_SESSION_COMPARE,
    APP_MODE_STORAGE_HEALTH,
    APP_MODE_EVENT_LOG,
    APP_MODE_ONBOARDING,
    APP_MODE_VIDEO_PLAYER,
    APP_MODE_PHOTO_VIEWER,
    APP_MODE_REBOOT,
    APP_MODE_SHUTDOWN
};

enum RadioBand : uint8_t {
    RADIO_BAND_24_GHZ = 0,
    RADIO_BAND_SUB_GHZ
};

enum JammerTarget {
    JAM_TARGET_WIFI = 0,
    JAM_TARGET_BT,
    JAM_TARGET_BLE_ADV,
    JAM_TARGET_BLE_DATA,
    JAM_TARGET_ALL,
    JAM_TARGET_ZIGBEE
};

enum AnalyzerBand {
    SCAN_BAND_ALL = 0,
    SCAN_BAND_WIFI,
    SCAN_BAND_BT
};

enum AnalyzerRadioMode {
    ANALYZER_RADIO_FAST = 0,
    ANALYZER_RADIO_DIVERSITY,
    ANALYZER_RADIO_1,
    ANALYZER_RADIO_2
};

enum ScanProfile {
    SCAN_PROFILE_FAST = 0,
    SCAN_PROFILE_BALANCED,
    SCAN_PROFILE_DEEP,
    SCAN_PROFILE_CUSTOM
};

enum AnalyzerTraceMode {
    ANALYZER_TRACE_LIVE = 0,
    ANALYZER_TRACE_AVERAGE,
    ANALYZER_TRACE_MAX,
    ANALYZER_TRACE_DELTA,
    ANALYZER_TRACE_COUNT
};

enum DisplayThemeId {
    DISPLAY_THEME_CYBER = 0,
    DISPLAY_THEME_OCEAN,
    DISPLAY_THEME_AMBER,
    DISPLAY_THEME_MATRIX,
    DISPLAY_THEME_VIOLET,
    DISPLAY_THEME_ICE,
    DISPLAY_THEME_FLIPPER,
    DISPLAY_THEME_RETRO,
    DISPLAY_THEME_TERMINAL,
    DISPLAY_THEME_NEON,
    DISPLAY_THEME_COUNT
};

enum MenuLayout : uint8_t {
    MENU_LAYOUT_GRID = 0,
    MENU_LAYOUT_LIST,
    MENU_LAYOUT_COUNT
};

constexpr int WATERFALL_ROWS = 24;
constexpr int RF_EVENT_COUNT = 8;

struct RfEvent {
    unsigned long timestampMs = 0;
    uint8_t channel = 0;
    uint8_t level = 0;
    uint8_t channelCount = 0;
    uint8_t durationSweeps = 0;
};
